version: "3.9"

services:
  postgres:
    image: "postgres:16"
    restart: "always"
    environment:
      - POSTGRES_DB=main
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    ports:
      - "5432:5432"